[package]
name = "fhast-gui"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
egui = "0.31"
eframe = { version = "0.31", default-features = false, features = ["wgpu", "default_fonts"] }
fhast-core = { path = "../fhast-core" }
fhast-ipc = { path = "../fhast-ipc" }
serde = "1"
serde_json = "1"
tokio.workspace = true

[target.'cfg(windows)'.dependencies]
eframe = { version = "0.31", default-features = false, features = ["glow", "default_fonts"] }
tray-icon = "0.20"

[target.'cfg(target_os = "linux")'.dependencies]
eframe = { version = "0.31", default-features = false, features = ["x11", "wayland"] }
gtk = "0.18"
tray-icon = { version = "0.20", features = ["default"] }
