[package]
name = "fhast-gui"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
eframe = "0.31"
egui = "0.31"
fhast-core = { path = "../fhast-core" }
fhast-ipc = { path = "../fhast-ipc" }
tokio.workspace = true
tray-icon = "0.20"